### ISSUE TITLE
SecureCRT 9.0 + SecureFX 9.0 正式版（macOS，Linux 和 Windows 特别许可版） - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#121]
https://sysin.org/article/securecrt-9/ 

  SecureCRT 9.0 + SecureFX 9.0 正式版（macOS，Linux 和 Windows 特别许可版） - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by LoveyCat** [comment]
感谢，但是macOS版本不是特别版呢

**Comment by netgc** [comment]
> @LoveyCat
> 感谢，但是macOS版本不是特别版呢

那应该叫什么版呢？

**Comment by Linyuxujun** [comment]
感谢，许可只有一年，一年之后是不是自己失效了?

**Comment by netgc** [comment]
> @Linyuxujun
> 感谢，许可只有一年，一年之后是不是自己失效了?

都写了是特别版，亲，有效期是花钱购买正版的人考虑的问题😄

**Comment by xyzzen** [comment]
英语很差的弱弱问一句,这东西有汉化版的吗

**Comment by kinkim** [comment]
用过最完美的版本

**Comment by kinkim** [comment]
版主有没有打算跟进9.1版？
