### ISSUE TITLE
VMware vSphere 7 Update 1 发布！ - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#13]
https://sysin.org/article/VMware-vSphere-7-Update-1/ 

  VMware vSphere 7 Update 1 发布！ - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by wjx0912** [comment]
请问下。是enterprise版吗？

**Comment by netgc** [comment]
> @wjx0912
> 请问下。是enterprise版吗？

软件介质是通用的，版本取决于许可（序列号），如果有Enterprise Plus版本的许可，输入序列号即可。

**Comment by wjx0912** [comment]
@netgc 
明白。谢谢啦
