### ISSUE TITLE
macOS Big Sur 11.3.1 (20E241) Boot ISO 镜像（可引导） - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#130]
https://sysin.org/article/macOS-Big-Sur-boot-iso/ 

  macOS Big Sur 11.3.1 (20E241) Boot ISO 镜像（可引导） - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by supermansaga** [comment]
谢谢。试了11.3.1，依然无法在vmware 16里面安装成功。总是会让选择startup disk，但又半天没结果。退出回到update assistant，也是无法更新。wifi已经一开始默认的NAT，应该不需要额外设置。想不明白了。
