### ISSUE TITLE
PAN-OS 10.0 VM 下载，全球首个基于机器学习的新一代防火墙 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#148]
https://sysin.org/article/DL-PAN-OS-10-VM/ 

  PAN-OS 10.0 VM 下载，全球首个基于机器学习的新一代防火墙 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by zenkl2628** [comment]
ovf的登录密码多少呢???為什麽沒有密碼?????????
