### ISSUE TITLE
macOS Big Sur 11.6.2 (20G314) 正式版 ISO、DMG、IPSW 下载

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#159]
https://sysin.org/blog/macOS-Big-Sur/ 

  macOS Big Sur 11.6.2 (20G314) 正式版 ISO、DMG、IPSW 下载 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by doomvampire** [comment]
没有hash校验值吗，楼主

**Comment by netgc** [comment]
> @doomvampire
> 没有hash校验值吗，楼主

新版加上了，要跟时间赛跑，没来得及😄
