### ISSUE TITLE
VMware ESXi 7.0 U2 SLIC & Unlocker USB 网卡驱动集成镜像 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#168]
https://sysin.org/article/vmware-esxi-7-u2-usb-nic/ 

  VMware ESXi 7.0 U2 SLIC & Unlocker USB 网卡驱动集成镜像 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by wzh4809** [comment]
大佬能不能出个带aqc107万兆驱动的

**Comment by netgc** [comment]
> @wzh4809
> 大佬能不能出个带aqc107万兆驱动的

似乎没有 ESXi 7.0 的驱动，[6.7 的驱动](https://my.vmware.com/en/web/vmware/downloads/details?downloadGroup=DT-ESXI67-MARVELL-ATLANTIC-1020&productId=742)或者[这里](https://github.com/Aquantia/AQtion-esxi/releases)看反馈可能适用 7.0，你直接安装看看，或许是可以。
