### ISSUE TITLE
VMware ESXi 7.0 U2 SLIC & Unlocker Intel NUC 专用镜像 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#169]
https://sysin.org/article/vmware-esxi-7-u2-nuc/ 

  VMware ESXi 7.0 U2 SLIC & Unlocker Intel NUC 专用镜像 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by FaintGhost** [comment]
想请问一下站长有没有遇到这种样的问题，机型是NUC11PAHi5内存32G。我开的虚拟机在开了一段时间之后在管理页面看内存消耗会变满，刚启动的时候是正常的，过一段时间不管分配多少内存，已消耗内存就会显示为满，但是好像也不影响使用，重新启动虚拟机后，内存消耗的使用又会正常显示。不知道具体是显示bug还是真的吃了那么多内存。

**Comment by netgc** [comment]
> @FaintGhost
> 想请问一下站长有没有遇到这种样的问题，机型是NUC11PAHi5内存32G。我开的虚拟机在开了一段时间之后在管理页面看内存消耗会变满，刚启动的时候是正常的，过一段时间不管分配多少内存，已消耗内存就会显示为满，但是好像也不影响使用，重新启动虚拟机后，内存消耗的使用又会正常显示。不知道具体是显示bug还是真的吃了那么多内存。

笔者没有 NUC11 机型，所以暂时没有遇到过，你可以登录 ESXi shell 用 esxtop 命令查看一下是否真的内存占满或者是那个进程占用的，或许有所帮助。
