### ISSUE TITLE
如何彻底禁止 macOS Catalina 自动更新，去除更新标记和通知 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#20]
https://sysin.org/article/Disable-macOS-Update/ 

  如何彻底禁止 macOS Catalina 自动更新，去除更新标记和通知 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by shorpenlee** [comment]
自打apple屏蔽了terminal禁止更新的命令行，只有博主提供的方法有用！！谢谢！！想问问有没有什么办法一起屏蔽app store的更新，一直推送，要烦死了！
