### ISSUE TITLE
在不受支持的 Mac 上安装 macOS Monterey 12 - sysin | SYStem INside | 数据中心系统内幕

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#236]
https://sysin.org/blog/install-macos-12-on-unsupported-mac/ 

  在不受支持的 Mac 上安装 macOS Monterey 12 - sysin：SYStem INside，数据中心系统内幕

**Comment by PookGai** [comment]
站长，太犀利了！让老机器依然能吃上新版本系统，静候蓝牙的修复！

**Comment by jiejays** [comment]
大佬求救，安装的wifi patch的时候出现以下代码，总是安装失败：

Checking patch to volume。。。

Make sure to run the script with path / to / PatchSystem.sh "NAME-OF-BIG-SUR-VOLUME"
No volume was specified on the command line or the volume selected is invalid

多谢大佬！

**Comment by rocky930215** [comment]
站长，patch对正式版安装文件好像失效了，能不能帮着确认一下
