### ISSUE TITLE
SecureCRT & SecureFX 9.1 macOS, Linux, Windows - sysin | SYStem INside | 数据中心系统内幕

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#248]
https://sysin.org/blog/securecrt-9-1/#61a4684ca92030731d1bb6b1 

  SecureCRT & SecureFX 9.1 macOS, Linux, Windows - sysin：SYStem INside，数据中心系统内幕

**Comment by shyhuhu4** [comment]
下载破解之后版本是否仍然需要手动输入license

**Comment by shyhuhu4** [comment]
找到license了

SecureCRT.lic
Is Eval License: N
Company: sysin.org
Serial Number: 03-67-372976
Expiration:
Issue Date: 10-10-2021
Name: SYSIN
__Pid__: 03,13
Version: 9.1.0 (build 2579)
__Vid__: 91
Key: AB5J3K RQDAH2 QG7CMR PS5DPZ AB21HN HU2NWM ZQXZ54 78DJ7R

SecureFX.lic
Is Eval License: N
Company: sysin.org
Serial Number: 06-32-007630
Expiration: 
Issue Date: 10-10-2021
Name: SYSIN
__Pid__: 06,13
Version: 9.1.0 (build 2579)
__Vid__: 91
Key: AD1RY9 5VDBCQ W1AEXD AVAMA8 AD2DAM HBBF7G EVCWWW V5XKKT
