### ISSUE TITLE
VMware ESXi 7.0 U3 SLIC 2.6 & Unlocker 集成 Intel NUC 网卡、USB 网卡和 NVMe 驱动 - sysin | SYStem INside | 数据中心系统内幕

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#275]
https://sysin.org/blog/vmware-esxi-7-u3-nuc-usb-nvme/#61ab4ba5a92030731d1fee0f 

  VMware ESXi 7.0 U3 SLIC 2.6 & Unlocker 集成 Intel NUC 网卡、USB 网卡和 NVMe 驱动 - sysin：SYStem INside，数据中心系统内幕

**Comment by averyfreeman** [comment]
Hi!  Can `esxi-unlocker-3.03` be used with `secureboot`?  Thanks!
