### ISSUE TITLE
如何在 Mac 和虚拟机上安装 macOS Big Sur 11 正式版 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#28]
https://sysin.org/article/how-to-install-macos-big-sur/ 

  如何在 Mac 和虚拟机上安装 macOS Big Sur 11.0 正式版 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by jia-zh** [comment]
楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？

**Comment by netgc** [comment]
> @jia-zh
> 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？

参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
联网操作即可

**Comment by rhtect** [comment]
楼主你好 使用esxi7.0 u1 配置好虚拟机后 启动进入蓝屏界面 boot maneger 选取启动项  没有看到苹果标志

**Comment by jia-zh** [comment]
> @netgc
> > @jia-zh
> > 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？
> 
> 参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
> 联网操作即可

已经都设置过了，联网以后也是【安装更新时出错】

**Comment by netgc** [comment]
> @rhtect
> 楼主你好 使用esxi7.0 u1 配置好虚拟机后 启动进入蓝屏界面 boot maneger 选取启动项  没有看到苹果标志

参看 5（3），使用本站的可启动 iso，如果硬件是 Mac 可以直接安装，如果硬件是非 Mac 的，需要 Unlock，第三方已经更新支持 7.0 U1。

**Comment by vivahu** [comment]
> @jia-zh
> > @netgc
> > > @jia-zh
> > > 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？
> > 
> > 参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
> > 联网操作即可
> 
> 已经都设置过了，联网以后也是【安装更新时出错】

同样现象，怀疑是安装更新需要的URL被墙了。我用手机联通4G给Macbook提供热点后能走完安装的进度条，然后对话框消失，放那里20分钟也不重启。强制关机重新引导，一切照旧，又提示需要更新。

**Comment by jia-zh** [comment]
> @vivahu
> > @jia-zh
> > > @netgc
> > > > @jia-zh
> > > > 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？
> > > 
> > > 参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
> > > 联网操作即可
> > 
> > 已经都设置过了，联网以后也是【安装更新时出错】
> 
> 同样现象，怀疑是安装更新需要的URL被墙了。我用手机联通4G给Macbook提供热点后能走完安装的进度条，然后对话框消失，放那里20分钟也不重启。强制关机重新引导，一切照旧，又提示需要更新。
> 
> PS. 已经按照4（2）步骤把T2芯片的配置改过，允许外置设备启动了。

各种方式都试过以后无效，去的售后，售后的也试了各种方法，也是无效，最后给我换了一个主板

**Comment by rhtect** [comment]
> @netgc
> > @rhtect
> > 楼主你好 使用esxi7.0 u1 配置好虚拟机后 启动进入蓝屏界面 boot maneger 选取启动项  没有看到苹果标志
> 
> 参看 5（3），使用本站的可启动 iso，如果硬件是 Mac 可以直接安装，如果硬件是非 Mac 的，需要 Unlock，第三方已经更新支持 7.0 U1。

多谢 回去试一下

**Comment by vivahu** [comment]
> > @vivahu
> > > @jia-zh
> > > > @netgc
> > > > > @jia-zh
> > > > > 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？
> > > > 
> > > > 
> > > > 参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
> > > > 联网操作即可
> > > 
> > > 
> > > 已经都设置过了，联网以后也是【安装更新时出错】
> > 
> > 
> > 同样现象，怀疑是安装更新需要的URL被墙了。我用手机联通4G给Macbook提供热点后能走完安装的进度条，然后对话框消失，放那里20分钟也不重启。强制关机重新引导，一切照旧，又提示需要更新。
> > PS. 已经按照4（2）步骤把T2芯片的配置改过，允许外置设备启动了。
> 
> 各种方式都试过以后无效，去的售后，售后的也试了各种方法，也是无效，最后给我换了一个主板

我昨晚最终成功了。用Big Sur启动U盘引导，并用手机的联通4G给Macbook提供热点。经过漫长的下载和多次重启后，总算引导成功并安装Big Sur成功。

总结：路由器级别翻墙很重要，毕竟U盘引导后无法安装个翻墙软件。之前失败几乎都是因为过程中必须联网下载，但用电信宽带时失败了，换联通4G总算成功了一次（也不是100%成功）

**Comment by netgc** [comment]
> @vivahu
> > > @vivahu
> > > > @jia-zh
> > > > > @netgc
> > > > > > @jia-zh
> > > > > > 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？
> > > > > 
> > > > > 
> > > > > 参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
> > > > > 联网操作即可
> > > > 
> > > > 
> > > > 已经都设置过了，联网以后也是【安装更新时出错】
> > > 
> > > 
> > > 同样现象，怀疑是安装更新需要的URL被墙了。我用手机联通4G给Macbook提供热点后能走完安装的进度条，然后对话框消失，放那里20分钟也不重启。强制关机重新引导，一切照旧，又提示需要更新。
> > > PS. 已经按照4（2）步骤把T2芯片的配置改过，允许外置设备启动了。
> > 
> > 各种方式都试过以后无效，去的售后，售后的也试了各种方法，也是无效，最后给我换了一个主板
> 
> 我昨晚最终成功了。用Big Sur启动U盘引导，并用手机的联通4G给Macbook提供热点。经过漫长的下载和多次重启后，总算引导成功并安装Big Sur成功。
> 
> 总结：路由器级别翻墙很重要，毕竟U盘引导后无法安装个翻墙软件。之前失败几乎都是因为过程中必须联网下载，但用电信宽带时失败了，换联通4G总算成功了一次（也不是100%成功）

谢谢分享，原来如此！我是在电信宽带重试了一次成功了（好像是第一次下载失败了），Apple的软件分发CDN按说已经在国内了，可能是网络环境比较复杂吧。

**Comment by vivahu** [comment]
> > @vivahu
> > > > @vivahu
> > > > > @jia-zh
> > > > > > @netgc
> > > > > > > @jia-zh
> > > > > > > 楼主，您好，出现【需要更新软件才能使用这个启动磁盘。】点击【更新】，一直显示【安装更新时出错】，怎么破？
> > > > > > 
> > > > > > 
> > > > > > 参看 3. （2）配备 Apple T2 安全芯片的电脑可能需要额外的操作
> > > > > > 联网操作即可
> > > > > 
> > > > > 
> > > > > 已经都设置过了，联网以后也是【安装更新时出错】
> > > > 
> > > > 
> > > > 同样现象，怀疑是安装更新需要的URL被墙了。我用手机联通4G给Macbook提供热点后能走完安装的进度条，然后对话框消失，放那里20分钟也不重启。强制关机重新引导，一切照旧，又提示需要更新。
> > > > PS. 已经按照4（2）步骤把T2芯片的配置改过，允许外置设备启动了。
> > > 
> > > 
> > > 各种方式都试过以后无效，去的售后，售后的也试了各种方法，也是无效，最后给我换了一个主板
> > 
> > 
> > 我昨晚最终成功了。用Big Sur启动U盘引导，并用手机的联通4G给Macbook提供热点。经过漫长的下载和多次重启后，总算引导成功并安装Big Sur成功。
> > 总结：路由器级别翻墙很重要，毕竟U盘引导后无法安装个翻墙软件。之前失败几乎都是因为过程中必须联网下载，但用电信宽带时失败了，换联通4G总算成功了一次（也不是100%成功）
> 
> 谢谢分享，原来如此！我是在电信宽带重试了一次成功了（好像是第一次下载失败了），Apple的软件分发CDN按说已经在国内了，可能是网络环境比较复杂吧。

是的，其实电信和联通网络都不是100%能成功的，但是如果全程走翻墙链路成功率就很高了，这要求路由器级别翻墙。说白了还是苹果的CDN做的不好。

**Comment by meowlgm** [comment]
同样的内容同样的资源，有个网站却要付费。

**Comment by netgc** [comment]
> @meowlgm
> 同样的内容同样的资源，有个网站却要付费。

本文是原创文章。哪个网站还要付费？
