### ISSUE TITLE
JetBrains Rider 2021.3 (macOS Intel x64/Apple M1, Linux, Windows) with Crack - sysin | SYStem INside | 数据中心系统内幕

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#288]
https://sysin.org/blog/jetbrains-rider-2021/ 

  JetBrains Rider 2021.3 (macOS Intel x64/Apple M1, Linux, Windows) with Crack - sysin：SYStem INside，数据中心系统内幕

**Comment by YamChark** [comment]
大佬 这个rider激活到什么时候？

**Comment by netgc** [comment]
> @YamChark
> 大佬 这个rider激活到什么时候？

尊敬的读者，您好，千万不要在以“大佬”这个说法来侮辱别人了，即使马云马化腾你叫人家大佬，人家也不可能高兴。文明社会你我共建，谢谢。

**Comment by YamChark** [comment]
> @netgc
> > @YamChark
> > 大佬 这个rider激活到什么时候？
> 
> 尊敬的读者，您好，千万不要在以“大佬”这个说法来侮辱别人了，即使马云马化腾你叫人家大佬，人家也不可能高兴。文明社会你我共建，谢谢。


> @netgc
> > @YamChark
> > 大佬 这个rider激活到什么时候？
> 
> 尊敬的读者，您好，千万不要在以“大佬”这个说法来侮辱别人了，即使马云马化腾你叫人家大佬，人家也不可能高兴。文明社会你我共建，谢谢。
好的 哥
