### ISSUE TITLE
VMware ESXi 7.0 SLIC 2.5 / macOS / LegacyCPU MOD ISO 百度网盘 下载 - System Inside | 数据中心：系统、平台和应用交付

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#3]
https://sysin.org/article/Download-VMware-ESXi-7.0-MOD/ 

  VMware ESXi 7.0 SLIC 2.5 / macOS / LegacyCPU MOD ISO 百度网盘 下载 - System Inside | 数据中心：系统、平台和应用交付

**Comment by aetaf** [comment]
请问82575eb网卡驱动如何封装到7.0，谢谢。
