### ISSUE TITLE
macOS Big Sur 11 可启动 ISO 镜像 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#37]
https://sysin.org/article/macOS-Big-Sur-boot-iso/ 

  macOS Big Sur 11.0.1（20B29）可启动 ISO 镜像 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by G0561** [comment]
兄弟，用你的11.0.1  升级11.1 怎么不成功啊？ 老提示 更新出错，不然就是“目前状态下，当前设备配置和目标对于安装无效，请再试一次”

**Comment by supermansaga** [comment]
这种ISO正是我这种懒人小白需要的。传统的cdr已经没人做了。DMG又不被VMWARE支持。谢谢。不过，为什么我装着装着，会卡在Select the system you want to use to start up your computer的界面呢？谢谢

**Comment by cycncn** [comment]
请问这个镜像可以在windows上安装吗，谢谢up！

**Comment by netgc** [comment]
> @cycncn
> 请问这个镜像可以在windows上安装吗，谢谢up！

经过验证的软件支持：Windows：[VMware Workstation 16](https://www.sysin.org/article/Download-VMware-Workstation-16/)

**Comment by osmanage** [comment]
该镜像顺利在ESXi7u1上安装成功，请教如何为其补vmtool？网上我去找了macOS的，版本对Big Sur来说稍微老了一点点，我没找到新的。

**Comment by osmanage** [comment]
可能是没有vmtool的缘故（认不到驱动显卡之类），我安装虽然成功，但是屏幕分辨率只有1024*768，分辨率被固定了不能修改。

**Comment by netgc** [comment]
> @osmanage
> 该镜像顺利在ESXi7u1上安装成功，请教如何为其补vmtool？网上我去找了macOS的，版本对Big Sur来说稍微老了一点点，我没找到新的。

[在 macOS 虚拟机中手动安装 VMware Tools](https://docs.vmware.com/cn/VMware-Tools/11.2.0/com.vmware.vsphere.vmwaretools.doc/GUID-FC74F5F1-ECC1-4C1C-AA25-7C9AF2DC2ADB.html)

vSphere Client 	清单 > 虚拟机 > 客户机 > 安装/升级 VMware Tools 并选择交互式 Tools 安装或交互式 Tools 升级

**Comment by G0561** [comment]
老铁 11.2.2 啥时候更新一下啊， 非常感谢

**Comment by G0561** [comment]
老铁，11.2.3  ISO 什么时候出啊，在线等
