### ISSUE TITLE
VMware NSX-T Data Center 3.1 发布 - 全栈网络和安全虚拟化 - sysin - System Inside

### ISSUE THREAD

**Issue by netgc** [netgc/gitalk#98]
https://sysin.org/article/vmware-nsx-t-3/ 

  VMware NSX-T Data Center 3.1 发布 - 全栈网络和安全虚拟化 - sysin | System Inside | 数据中心：系统、平台和应用交付

**Comment by snflowercn** [comment]
32.版本本月16号已经发布，麻烦更新，谢谢~~
